version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 9912:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
  redis:
    image: 'redis:latest'
    ports:
      - 6380:6379
